spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
